# Generated by Django 5.0.6 on 2024-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='soglasie',
            field=models.BooleanField(default=False),
        ),
    ]
