# Generated by Django 5.0.6 on 2024-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pochta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50, verbose_name='Тема письма')),
                ('mail', models.CharField(max_length=50, verbose_name='Почта отправителя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
