# Generated by Django 5.0.6 on 2024-06-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблица'},
        ),
    ]
