# Generated by Django 5.0.6 on 2024-06-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pochta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pochta',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
