# Generated by Django 5.0.6 on 2024-06-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_pochta_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.png', upload_to='user_img', verbose_name='Фото Пользователя'),
        ),
    ]
